name: Trigger Workflows

on:
  push:
    branches:
      - main

jobs:
  trigger-tests:
    uses: ./.github/workflows/tests.yml

  trigger-terraform:
    needs: trigger-tests
    uses: ./.github/workflows/terraform.yml
